FROM python:2.7
ENV PYTHONUNBUFFERED 1

RUN mkdir /logs
RUN mkdir /requirements
WORKDIR /requirements
ADD requirements.txt /requirements/
RUN pip install --upgrade pip
RUN pip install -r requirements.txt -U

WORKDIR /code
